# Generated by Django 2.2 on 2019-10-27 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketName', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=200)),
                ('purchasedTime', models.DateTimeField(default=datetime.datetime(2019, 10, 27, 14, 7, 55, 904460))),
                ('status', models.CharField(max_length=100)),
                ('busCapacity', models.IntegerField()),
            ],
        ),
    ]
